trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Bestill_dev
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '.'
        buildFlavour: 'dev'
        entryPoint: 'lib/main_dev.dart'
        iosCodesign: false
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: "dev-android.jks"
        apksignerKeystorePassword: "Pa$$w0rd1"
        apksignerKeystoreAlias: "dev-bestill"
        apksignerKeyPassword: "Pa$$w0rd1"
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
        OverWrite: true
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'drop'
    