trigger:
  branches:
    include:
    - dev
stages:
- stage: __default
  jobs:
  - job: Bestill_dev
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '.'
        buildFlavour: 'dev'
        entryPoint: 'lib/main_dev.dart'
        iosCodesign: false
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: "dev-android.jks"
        apksignerKeystorePassword: "Pa$$w0rd1"
        apksignerKeystoreAlias: "dev-bestill"
        apksignerKeyPassword: "Pa$$w0rd1"
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
        OverWrite: true
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'drop'
    - task: InstallAppleCertificate@2
      displayName: "Install Apple p12 cert"
      inputs:
        certSecureFile: "second-distribution-cert.p12"
        certPwd: $(library.passwordCert)
        keychain: "temp"
        deleteCert: true
    - task: InstallAppleProvisioningProfile@1
      displayName: "Install Apple Mobile Provisioning Profile"
      inputs:
        provisioningProfileLocation: "secureFiles"
        provProfileSecureFile: "match_AdHoc_orgsecondbestilldev.mobileprovision"
        removeProfile: true
    - task: Xcode@5
      displayName: "Code sign ipa for Distribution"
      inputs:
        actions: "build"
        xcWorkspacePath: "Runner.xcworkspace"
        scheme: "dev"
        sdk: "iphoneos"
        configuration: "release"
        packageApp: true
        signingOption: "manual"
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
        provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.ipa'
        targetFolder: '$(build.artifactStagingDirectory)'
        OverWrite: true
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'drop'

